config/routes.rb
RubyPG::Application.routes.draw do

  root :to => 'application#index'

  resources :adventures, :only => [:index, :show]
  resources :games, :only => [:index, :new,:destroy] do
    member do
      get :play
      get :move
      get :turn
    end
  end

end

app/models/game.rb
class Game < ActiveRecord::Base

  belongs_to :adventure
  
  has_many :levels, :through => :adventure
 
  has_many :characters, :dependent => :destroy

  belongs_to :current_character, :class_name => 'Character', 
             :foreign_key => :current_character_id

  has_one :current_level, 
          :through => :current_character, 
          :class_name => 'Level', :source => :current_level
  
  serialize :player_order


  def Game.start_adventure(adventure,ip="localhost")
    adventure = Adventure.find(adventure) if adventure.is_a?(Integer) 
    raise "You need an adventure to start an adventure!" unless adventure.is_a?(Adventure)
    Game.find_all_by_ip_address(ip).each{|x|x.update_attribute(:current, false)}
    game = Game.create!(:adventure_id => adventure.id,
                        :name => adventure.name,
                        :ip_address => ip,
                        :current => true)
    game.clone_adventure_characters
    game.set_player_order
    return game
  end

  def set_player_order
    character_ids = self.players.order('speed desc').collect{|x|x.id}
    self.update_attributes(
      :player_order => character_ids,
      :current_character_id => character_ids[0]
    )
  end

  def clone_adventure_characters
    characters.destroy_all
    adventure.characters.each do |character|
      new_character = character.dup
      new_character.adventure_id = nil
      new_character.game_id = self.id
      new_character.save!
      character.character_skills.each do |skill|
        new_character.character_skills.create(:skill_id => skill.skill_id, 
                                              :level => skill.level)
      end
    end
  end

  def players
    characters.where(:player => true)
  end

  def enemies
    characters.where(:player => false)
  end

  attr_accessor :character_ids_to_remove

  def clear_dead(messages)
    self.character_ids_to_remove ||= []
    self.characters.where('health <= 0').each do |character|
      self.character_ids_to_remove << character.id
      messages << character.kill
    end
    messages
  end

  def finish_turn
    messages = []
    paths = []
    # end the players turn
    messages << current_character.finish_turn
    # Check for dead characters
    messages = clear_dead(messages)
    # run automatic turns for enemis
    current_character.current_level.enemies.where(:game_id => self.id).each do |enemy|
      message, path = enemy.automatic_turn
      messages << message
      paths << path
    end
    # Check for dead characters
    messages = clear_dead(messages)
    # Move to next players turn
    update_attributes(:current_character_id => (player_order[(player_order.index(current_character_id) + 1)] || player_order[0]))
    messages << "<b>It's #{current_character.name}'s turn.<b/>"

    return messages.flatten, paths
  end
  

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  before_filter :get_game

  # redirects to current game in play
  def index
    @games = Game.find_all_by_ip_address(request.remote_ip)
  end

  def destroy
    @game = Game.find(params[:id])
    @game.destroy
    flash[:message] = "Successfully deleted that game."
    if Game.find_all_by_ip_address(request.remote_ip).any?
      redirect_to games_path
    else
      redirect_to adventures_path
    end
  end


  def new
    if params[:adventure_id] and @adventure = Adventure.find(params[:adventure_id])
      game = Game.start_adventure(@adventure, request.remote_ip)
      redirect_to play_game_path(game)
    else
      flash[:notice] = "Choose an adventure to start a game."
      redirect_to adventures_path
    end
  end

  def play
    if params[:id]
      @game = Game.find(params[:id])
      unless @game == @current_game
        Game.find_all_by_ip_address_and_current(request.remove_ip,true).each do |game|
          game.update_attribute :current, false
        end
        @game.update_attribute :current, true
      end
    end
    unless @current_game
      flash[:notice] = "You have no current games, choose an adventure to start one."
      redirect_to adventures_path
    end
  end

  def move
    @messages = []
    raise "Co ordinate is not valid" unless params[:coord] and params[:coord][0..0] == '[' and params[:coord][-1..-1] == ']'
    @coord = eval params[:coord]
    @path = @game.current_character.move(@coord)
    if @path
      @messages << "#{@game.current_character.name} moves to #{@coord.inspect}"
    else
      @messages << "#{@game.current_character.name} can not move to #{@coord.inspect}."
    end
  end

  def turn
    characters = @game.characters.collect{|x|x.id}
    # skill
    case params[:skill]
      when "end"
        @messages, @paths = @game.finish_turn
      when "use_door"
        @messages, @extra_js = @game.current_character.use_door
      else
        @skill = @game.current_character.skills.find(params[:skill])
        @messages = @game.current_character.use_skill(@skill,params[:target])
        messages, @paths = @game.finish_turn
        @messages = [@messages, messages].flatten
    end
    @game.reload
    @created_characters = @game.characters.where(["id not in (?)",characters])
  end

  def get_game
    @game = @current_game
  end

end

app/helpers/game_helper.rb
module GameHelper
end

app/views/games/_character_token.html.erb
<div class='character <%="#{character.character_class.name.downcase}"%>' 
     id='character_<%= character.id%>' 
     title="<%= character.tooltip %>">
  <div class=health_bar></div>
  <div class=skill_bar></div>
</div>

<script type='text/javascript'>
  set_health(<%= character.id%>, <%= character.health_percent %>);
  set_skill(<%= character.id%>, <%= character.skill_percent %>);
</script>

app/views/games/_game_summary.html.erb
<div class='game_summary'>
  <h3><%= @game.adventure.name %> - Started <%= short_date(@game.created_at) %></h3>
  <h4>Players</h4>
  <% game.players.each do |player| %>
    <b><%= player.name %></b><br/>
    <b>Level</b> <%= player.level %><br/>
    <b>Health</b> <%= player.health %>/<%= player.max_health %><br/>
    <b>skill</b> <%= player.skill %>/<%= player.max_skill %><br/>
  <% end %>
  <%= link_to "Play", play_game_path(:id => game.id), :class => 'btn btn-success' %>
  <%= link_to "Delete", game_path(:id => game.id), :class => 'btn btn-danger', :method => :delete %>
</div>

app/views/games/_level_grid.html.erb
<% characters = [] %>
<div class='level_holder' id='<%= level.id %>' style='display:none;' >
  <h3><%= level.name %></h3>
  <table class='level_grid' id='lvl_<%= level.id%>'>
    <% level.rows.times do |row|%>
      <tr>
        <% row += 1 %>
        <% level.columns.times do |column| %>
          <% column += 1 %>
          <% coord = [column, row] %>
          <% klasses = "" %>         
          <% id = "" %>
          <% obstacle = level.obstacle_positions.include?(coord)%>
          <% klasses << "obstacle " if obstacle %>
          <% characters = level.characters.at(@current_game.id, row, column) %> 
          <% if door = level.doors.at(row, column) %>
            <% klasses << 'door' %>
            <% id << "door_#{door.id}" %>
          <% end %>
	  <td>
            <div id='<%= id %>' class='<%= klasses %>'></div>
            <% if characters %>
              <% characters.each do |character| %>
                <%= render :partial => 'character_token', :locals => {:character => character} %>
              <% end %>
              <% characters = [] %>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </table>
</div>

app/views/games/_show_messages.js.erb
<% if @messages %>
  <% @messages.each_with_index do |message,index| %>
    setTimeout(function(){show_message("<%= raw message%>");},<%= index * 150 %>);
  <% end %>
<% end %>

app/views/games/_turn_menu.html.erb
<% character ||= @game.current_character %>
<div class='turn_menu' style='height:100px;'>
  <ul class="nav nav-pills nav-stacked">
    <% if character.on_door? %>
      <li><%= link_to "Go Through Door", turn_game_path(@game.id, :skill => 'use_door'), :remote => true %></li>
    <% end %>
    <li class='dropdown'>
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">Actions<span class="caret"></span></a>
      <ul class="dropdown-menu">
        <% character.skills.each do |skill| %>
          <% if skill.skill_cost <= character.skill %>
            <% if character.skill_targets(skill).any? %>           
              <li class='nav-header' 
                  title='<%= skill.tooltip %>'>
                <%= skill.menu_label %>
              </li>
              <% character.skill_targets(skill).each do |target| %>
                <li>
                  <%= link_to target.name, 
                      turn_game_path(@game.id, 
                                     :skill => skill.id, 
                                     :target => target.id), 
                      :remote => true %>
                </li>
              <% end %>
            <% else %>
              <li class='nav-header' 
                  title='<%= skill.tooltip %>'>
                <%= skill.menu_label %> (No Targets)
              </li>
            <% end %>
          <% else %>
              <li class='nav-header' 
                  title='<%= skill.tooltip %>'>
                <%= skill.menu_label %> (Not Enough Skill)
              </li>          
          <% end %>       
        <% end %>
      </ul>
    </li>
    <li><%= link_to "End Turn", turn_game_path(@game.id, :skill => 'end'), :remote => true %></li>
  </ul>
</div>

app/views/games/index.html.erb
<h1>Games</h1>
<p>Select a game to play or delete.</p>

<% @games.each do |game| %>
  <%= render :partial => 'game_summary', :locals => {:game => game} %>
<% end %>

app/views/games/move.js.erb
<%= render :partial => 'show_messages' %>
$('.turn_menu').html('<%= escape_javascript render :partial => 'turn_menu' %>');

//TODO move stuff
<% if @path %>
  <% @path.each_with_index do |coord,index| %>
    setTimeout(
      function(){
        // debugging line
        //show_message("<%= coord.inspect %>");
        move("#character_"+<%= @game.current_character_id %>,<%= raw coord.inspect %>);
      }, 
      <%=index * 150%>
    );
  <% end %>
<% end %>
<%= @game.current_character.current_turn_js_call%>

app/views/games/play.html.erb
<h1>Playing <%= @game.name %></h1>
<div class='row row-fluid'>
  <div class='span8'>
    <% @game.levels.each do |level| %>
      <%= render :partial => 'level_grid', :locals => {:level => level} %>
    <% end %>
  </div>
  <div class='span4' id='right_bar'>
    <%= render :partial => 'turn_menu', :locals => {:character => @game.current_character} %>
    <div class='play_messages' id='play_messages'>
  </div>
</div>

<script type='text/javascript'>
  <%= @game.current_character.current_turn_js_call %>
  $('#play_messages').height($('.level_holder').height()-$('.turn_menu').height());
</script>

app/views/games/turn.js.erb
<%= render :partial => 'show_messages' %>

<!-- refresh actions -->
$('.turn_menu').html('<%= escape_javascript render :partial => 'turn_menu' %>');

<%= @extra_js if @extra_js %>

<% if @created_characters and @created_characters.any? %>
  <% @created_characters.each do |character| %>
    <!-- add freshly created characters to the board-->
    spawn_character(<%= character.coord.inspect %>,
                    <%= character.level_id%>,
                    '<%=escape_javascript render :partial => 'character_token', :locals => {:character => character} %>'
    );
  <% end %>
<% end %>

<!-- enemies movements take place -->
<% times = [] %>
<% if @paths and @paths.any? %>
  <% @paths.each do |movement| %>
    <% movement.each do |character, path|%>
      <% if path %>

        <% path.each_with_index do |coord,index| %>
          setTimeout(
            function(){
              // debugging line
              //show_message("<%= coord.inspect %>");
              move("#<%= character %>",<%= raw coord.inspect %>);
            },
            <% time = index * 150 %>
            <% times << time %>
            <%=time%>
          );
        <% end %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

<!-- set health bars -->
<% @game.current_level.characters.each do |character| %>
  set_health(<%= character.id%>, <%= character.health_percent %>);
  set_skill(<%= character.id%>, <%= character.skill_percent %>);
  $('#character_<%= character.id%>').attr('title','<%= escape_javascript character.tooltip %>');
<% end %>

<!-- remove dead characters from the board -->
<% if @game.character_ids_to_remove %>
  <% @game.character_ids_to_remove.each do |id| %>
    set_health(<%= id %>, 0);
    setTimeout(function(){$('#character_<%= id %>').slideUp();},1000);
    setTimeout(function(){$('#character_<%= id %>').remove();},1500);
    <% times << 1500 %>
  <% end %>
<% end %>



setTimeout(function(){<%= @game.current_character.current_turn_js_call%>},<%= times.max || 0 %>);