config/routes.rb
RubyPG::Application.routes.draw do

  root :to => 'application#index'

  resources :adventures, :only => [:index, :show]
  resources :games, :only => [:index, :new,:destroy] do
    member do
      get :play
      get :move
      get :turn
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsPG</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= stylesheet_link_tag "bootstrap.min", :media => "all" %>
  <%= stylesheet_link_tag "bootstrap-responsive.min", :media => "all" %>
  <%= stylesheet_link_tag params[:controller][0..-2] %>

  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "jquery_ujs.js" %>
  <%= javascript_include_tag params[:controller][0..-2] %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class=holder>
    <div class=header>
      <div class=row-fluid>
        <div class="span8">
          <div id='header-logo'>
            Put an icon here, you moron!
          </div>
        </div>
        <div class=span4>
          <div id=menu>
            <ul class="nav nav-pills nav-stacked">
              <li class='<%= 'active' if params[:controller] == 'application' %>'>
                <%= link_to 'Home', root_path, :disabled => (params[:controller] == 'application') %>
              </li>
              <li class='<%= 'active' if params[:controller] == 'adventures' %>'>
                <%= link_to 'Adventures', adventures_path, :disabled => (params[:controller] == 'adventures') %>
              </li>
              <% if @running_games.any? %>
                <li class='<%= 'active' if params[:controller] == 'games' and params[:action] == 'index'%>'>
                  <%= link_to 'Select Game', games_path, :disabled => (params[:controller] == 'games') %>
                </li>
              <% end %>
              <% if @current_game %>
                <li class='<%= 'active' if params[:controller] == 'games' and params[:action] == 'play' %>'>
                  <%= link_to 'Play Game', play_game_path(@current_game), :disabled => (params[:controller] == 'games') %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <div id=main_site>
      <%= yield %>
    </div>
  </div>
</body>
</html>